### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by GremlingSS** [Dropshotz/SS13-Jukebox-Parser-Discord-Bot#2]
it just doesnt work :(
have you fixed it yet??

**Comment by GremlingSS** [comment]
ur using stolen assets >:(

**Comment by Dropshotz** [comment]
I literally handwrote it bruh

**Comment by GremlingSS** [comment]
https://github.com/Dropshotz/SS13-Jukebox-Parser-Discord-Bot/assets/68038883/a022f7b7-573a-40a8-9143-fcd73bd939ed
